services:
  producer:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gtfsrt-lia
    environment:
      - TZ=Europe/Paris
    ports:
      - "127.0.0.1:50002:3000"
    restart: unless-stopped
